language: go
go:
  - 1.11
  - 1.12
  - tip
before_install:
  - sudo pip install codecov
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
after_success:
  - bash <(curl -s https://codecov.io/bash)
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
sudo: required
